name: Code Coverage

# Run CI task on Push only for main branch, also on PR. 
on:
  push:
    branches:
      - main
      - development
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          script: ./gradlew app:combinedJacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          paths: ${{ github.workspace }}/app/build/reports/jacoco/combinedJacocoTestReport/combinedJacocoTestReport.xml
