name: Code Coverage

# Run CI task on Push only for main branch, also on PR. 
on:
  push:
    branches:
      - main
      - development
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run tests & Generate Coverage
        run: ./gradlew app:koverXmlReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ github.workspace }}/app/build/all-projects-reports/kover.xml
