name: Code Coverage

# Run CI task on Push only for main branch, also on PR. 
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          # Reactive Circus Emulator actually builds an emulator and runs your tests.
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew app:coveralls