name: Code Coverage

# Run CI task on Push only for main branch, also on PR. 
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew app:koverReport
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          paths: ${{ github.workspace }}/app/build/reports/kover/report.xml
          min-coverage-overall: 10
          min-coverage-changed-files: 20
